### ISSUE TITLE
Make Indentation Levels Great Again

### ISSUE THREAD

**Issue by FlaccidSnake** [huandney/Anki-Insert-Randomized-Lists#4]
Hello there
Love the addon and script, I like how it's compatible across platforms and it's not that hard to install. 
One thing I'd comment on though is that if I put a second level in the list—

> - Like
>     - This

—the child gets shuffled around with different parents. Multiple children get shuffled together (as in they stick together, they remain in the order they were... born), they're just kidnapped by different parents. 
Now I don't know what the universal use-case would be, maybe children stick with their original parents and are shuffled within the family, maybe they stick with the original parent and aren't shuffled, because (as in my case) I want to use the children to comment on the parents in quick-fire bullet-points. In either case, it seems more useful to have the children stick under the parents, since the indentation levels of bullet points traditionally denote relationships.

So it's not an issue per se, just something that would be nice if it was improved, if you have the time.
Cheers

**Comment by huandney** [comment]
Hi, I had never paid attention to that, it really makes more sense to keep father and children grouped together. I'll improve that!

**Comment by FlaccidSnake** [comment]
Poggers
